#!/usr/bin/env python

'''
Copyright [yyyy] [name of copyright owner]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'''
import rospy
from rospy.numpy_msg import numpy_msg
from shape_msgs.msg import Mesh
from visualization_msgs.msg import Marker
from geometry_msgs.msg import Point
from std_msgs.msg import ColorRGBA

from interactive_markers.interactive_marker_server import *
from interactive_markers.menu_handler import *
from visualization_msgs.msg import InteractiveMarkerControl
import copy
from tf.broadcaster import TransformBroadcaster
from tf.listener import TransformListener
import tf

import numpy as np
from stl import mesh

from interactive_geometry.ellipsoid_generator import *
from interactive_geometry.mesh_exporter import *
from interactive_geometry.utils import *
from interactive_geometry.interactive_marker_utils import  InteractiveMarkerUtils


menu_handler = MenuHandler()


if __name__ == '__main__':
    # Initialize node, publishers, and interactive marker server
    rospy.init_node('interactive_ellipsoid_node', anonymous=True)
    pub_marker = rospy.Publisher('mesh_marker', Marker, queue_size=10)


    server = InteractiveMarkerServer("basic_controls")
    broadcaster = TransformBroadcaster()
    listener = TransformListener()
    util = InteractiveMarkerUtils(server, broadcaster, pub_marker)
    position = Point(0, 0, 0)
    util.make6DofMarker( False, InteractiveMarkerControl.NONE, position, True)

    # 'commit' changes and send to all clients
    server.applyChanges()

    # create a timer to update the published transforms
#    rospy.Timer(rospy.Duration(0.01), util.frameCallback)

    broadcaster.sendTransform( (0, 0, 0), (0, 0, 0, 1.0), rospy.Time.now(), "base_link", "mesh_frame" )

    rate = rospy.Rate(1) # 10hz
    seq = 0
    while not rospy.is_shutdown():
        a = rospy.get_param('~a')
        b = rospy.get_param('~b')
        c = rospy.get_param('~c')

        # Generate the ellipse
        gen = EllipsoidGenerator(a, b, c)
        gen.generate_ellipsoid()
#         Rebroadcast the tf
        try:
            (trans,rot) = listener.lookupTransform("base_link", "mesh_frame", rospy.Time(0))
            broadcaster.sendTransform( trans, rot, rospy.Time.now(), "mesh_frame", "base_link",)
        except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            broadcaster.sendTransform( (0, 0, 0), (0, 0, 0, 1.0), rospy.Time.now(),  "mesh_frame", "base_link" )
            print("Resetting TF")
            continue

        # Add/Update mesh
        marker = Marker()
#        marker = to_triangle_marker_msg(gen.vertices, gen.faces, "world", seq, rospy.Time.now())
        marker = to_triangle_marker_msg(gen.vertices, gen.faces)

        # TODO: Move this into utility fnc above
        #Fill header
        marker.header.frame_id = "mesh_frame"
        marker.header.stamp = rospy.Time.now()
        marker.header.seq = seq
        seq += 1
        marker.ns = "interactive_geometry"
        marker.id = 0
        marker.type = Marker.TRIANGLE_LIST
        marker.action = Marker.ADD;
        marker.pose.position.x = 0;
        marker.pose.position.y = 0;
        marker.pose.position.z = 0;
        marker.pose.orientation.x = 0.0;
        marker.pose.orientation.y = 0.0;
        marker.pose.orientation.z = 0.0;
        marker.pose.orientation.w = 1.0;
        marker.scale.x = 1;
        marker.scale.y = 1;
        marker.scale.z = 1;
        marker.color.a = 1.0;
        marker.color.r = 1.0;
        marker.color.g = 1.0;
        marker.color.b = 1.0;
        marker.lifetime = rospy.Duration(0)
#        marker.lifetime = rospy.Time.now()
        marker.frame_locked = True






        pub_marker.publish(marker)
#        print("published mesh")
        rate.sleep()



#    export = MeshExporter()
#    export.mesh_to_stl(gen.vertices, gen.faces, "output.stl")


